version: '3.2'
services:
  web:
      build:
        context: .
        dockerfile: Dockerfile
      privileged: true
      ports:
        - "3000:3000"
        - "1234:1234" # Debugger port inside docker
